name: yukem_dashboard
description: Dashboard do yukem vendas




publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
#  Icons
  ant_icons: ^2.0.0-nullsafety.0
  ionicons: ^0.1.2
  cupertino_icons: ^1.0.2
#  Navegacao
#  path:
#  path_provider:
  share:
#  Internet
  http:
  web_socket_channel:
#  Utility
  provider:
  platform_device_id: ^1.0.1
  mask_text_input_formatter: ^2.1.0
  flutter_layout_grid: ^2.0.1
#  Sync Fusion
  syncfusion_flutter_core: 20.1.55
  syncfusion_flutter_charts: 20.1.55
#  syncfusion_flutter_datagrid: ^20.2.39
#  percent_indicator: ^3.3.0
flutter_localizations: 
  sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
  

flutter:


  uses-material-design: true